name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.7
  local_auth: ^2.2.0
  connectivity_plus: ^5.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  profile: ^0.0.1
  



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
