name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  confirm_dialog: ^1.0.3
  connectivity_plus: ^5.0.2
  excel: ^4.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.7
  http: ^1.2.1
  local_auth: ^2.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  profile: ^0.0.1
  shared_preferences: ^2.2.2
flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/icon/icon.png'
  adaptative_icon_background: 'assets/icon/icon.png'

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
